export const sampleTipps = [
  {
    id: 1,
    title: "Zeus tippek",
    available_tipps: 23,
    sum_tip_number: 134,
    rating: 4.6,
    winned_tip: 80,
    winned_money: "140.000 Ft",
    description:
      "13 éve foglakozom a tippekel, melyben 78%-os nyerési aránnyal váltam ismerté a Tippmesterek körében. Jelenlegi vagyonom nagyrészét csakis a sportfogadásnak köszönhetem!",
    color: "#1c1f40",
    cover: "",
    video: "",
  },
  {
    id: 2,
    title: "Menus tippek",
    available_tipps: 42,
    sum_tip_number: 239,
    description: "",
    rating: 4.9,
    winned_tip: 80,
    winned_money: "340.000 Ft",
    color: "#1c1f40",
    cover: "",
    video: "",
  },

  {
    id: 3,
    title: "Hermész tippek",
    available_tipps: 9,
    sum_tip_number: 150,
    rating: 4.7,
    winned_tip: 110,
    description: "",
    winned_money: "210.000 Ft",
    color: "#ff5733",
    cover: "",
    video: "",
  },
  {
    id: 4,
    title: "Hádész tippek",
    available_tipps: 7,
    sum_tip_number: 90,
    rating: 4.5,
    description: "",
    winned_tip: 60,
    winned_money: "120.000 Ft",
    color: "#2c3e50",
    cover: "",
    video: "",
  },
  {
    id: 5,
    title: "Poszeidón tippek",
    available_tipps: 3,
    sum_tip_number: 175,
    description: "",
    rating: 4.8,
    winned_tip: 140,
    winned_money: "280.000 Ft",
    color: "#3498db",
    cover: "",
    video: "",
  },
  {
    id: 6,
    title: "Apollón tippek",
    available_tipps: 1,
    sum_tip_number: 120,
    rating: 4.6,
    description: "",
    winned_tip: 95,
    winned_money: "200.000 Ft",
    color: "#f39c12",
    cover: "",
    video: "",
  },
  {
    id: 7,
    title: "Arész tippek",
    available_tipps: 22,
    sum_tip_number: 200,
    rating: 4.9,
    description: "",
    winned_tip: 170,
    winned_money: "350.000 Ft",
    color: "#e74c3c",
    cover: "",
    video: "",
  },
  {
    id: 8,
    title: "Dionüszosz tippek",
    available_tipps: 13,
    description: "",
    sum_tip_number: 80,
    rating: 4.4,
    winned_tip: 50,
    winned_money: "90.000 Ft",
    color: "#9b59b6",
    cover: "",
    video: "",
  },
  {
    id: 9,
    title: "Héra tippek",
    available_tipps: 7,
    sum_tip_number: 140,
    description: "",
    rating: 4.7,
    winned_tip: 110,
    winned_money: "230.000 Ft",
    color: "#e67e22",
    cover: "",
    video: "",
  },
  {
    id: 10,
    title: "Athéné tippek",
    available_tipps: 19,
    description: "",
    sum_tip_number: 160,
    rating: 4.8,
    winned_tip: 130,
    winned_money: "260.000 Ft",
    color: "#16a085",
    cover: "",
    video: "",
  },
];
